#release configuration
#Sat Apr 21 21:14:22 CEST 2012
project.dev.eu.debooy\:sitemanager=0.4.1-SNAPSHOT
project.scm.eu.debooy\:sitemanager.developerConnection=scm\:svn\:http\://svn.debooy.eu/svn/SiteManager/trunk
project.rel.eu.debooy\:sitemanager=0.4.0
scm.tag=sitemanager-0.4.0
scm.url=scm\:svn\:http\://svn.debooy.eu/svn/SiteManager/trunk
preparationGoals=clean verify
project.scm.eu.debooy\:sitemanager.connection=scm\:svn\:http\://svn.debooy.eu/svn/SiteManager/trunk
scm.commentPrefix=[maven-release-plugin] 
exec.additionalArguments=-P nexus,sonar,sonar
project.scm.eu.debooy\:sitemanager.tag=HEAD
completedPhase=scm-commit-release
